### ISSUE TITLE
ImportError: /home/ssl/miniconda3/envs/gs_avatar/lib/python3.10/site-packages/diff_gaussian_rasterization/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs

### ISSUE THREAD

**Issue by Dragon2938734** [aipixel/GaussianAvatar#22]
excuse me, i meet this bug and are confused with it. Do you konw the reason? I follow the environment.yml to set my conda environment. Thank you!

Traceback (most recent call last):
  File "/home/ssl/autodl-tmp/GaussianAvatar/train.py", line 13, in <module>
    from model.avatar_model import AvatarModel
  File "/home/ssl/autodl-tmp/GaussianAvatar/model/avatar_model.py", line 14, in <module>
    from gaussian_renderer import render_batch
  File "/home/ssl/autodl-tmp/GaussianAvatar/gaussian_renderer/__init__.py", line 6, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/home/ssl/miniconda3/envs/gs_avatar/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /home/ssl/miniconda3/envs/gs_avatar/lib/python3.10/site-packages/diff_gaussian_rasterization/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs

**Comment by Dragon2938734** [comment]
ok , i have solve it.
